### PR TITLE
Ignored Pycache files

### PR DESCRIPTION
**Pull request by sathyanmadhavan**

### CODE REVIEW

**Review by shivahari — COMMENTED** [review]
The change looks good.
How will you test this new directive you have added?

**Comment by sathyanmadhavan** [comment]
> The change looks good. How will you test this new directive you have added?

There is command `git check-ignore` to test if gitignore is working

**Comment by shivahari** [comment]
> > The change looks good. How will you test this new directive you have added?
> 
> There is command `git check-ignore` to test if gitignore is working

Nice. I did not know about `git check-ignore`. Can you run that command and post the output here.

**Comment by sathyanmadhavan** [comment]
> > > The change looks good. How will you test this new directive you have added?
> > 
> > 
> > There is command `git check-ignore` to test if gitignore is working
> 
> Nice. I did not know about `git check-ignore`. Can you run that command and post the output here.

git check-ignore -v *
.gitignore:7:__pycache__/       __pycache__
.gitignore:3:*.log      geckodriver.log

This is the output when we run the command

**Comment by shivahari** [comment]
> > > > The change looks good. How will you test this new directive you have added?
> > > 
> > > 
> > > There is command `git check-ignore` to test if gitignore is working
> > 
> > 
> > Nice. I did not know about `git check-ignore`. Can you run that command and post the output here.
> 
> `git check-ignore -v * ` .gitignore:7:**pycache**/ **pycache** .gitignore:3:*.log geckodriver.log
> 
> This is the output when we run the command

Neat. Okay

**Pull request merged**
